package org.railinc.shipping
import java.lang.Number;


rule "bolPriceTotal"
	dialect "mvel"
	no-loop true
	ruleflow-group "bolPricing"
    when
        abol:BillOfLading()
        not Shipment(billOfLadingParent==abol, state!="accepted")
        totalPrice: Number( floatValue > 0 )
        	from accumulate( Shipment(billOfLadingParent==abol, priceVal:priceDollars), sum( priceVal ) )
    then
        abol.setPriceDollars( totalPrice.floatValue());
        update(abol)
        System.out.println("Set bol price");
end

rule "bolAccept" 
  no-loop true
  ruleflow-group "bolValidation"
  when
    abol:BillOfLading(state=="in-process")
    not Shipment(billOfLadingParent==abol, state!="accepted")
  then
    abol.setState("accepted");
    update(abol);
end
